# Sets all open pull requests against staging to be allowed to be merged
# Purpose is to prevent expensive re-runs of staging to production PR tests caused by pushes
# It is triggered when a pull request is closed against production.

name: Set staging to production mergability as success
on:
  pull_request:
    branches:
      - 'main'
    types:
      - 'closed'
jobs:
  Job:
    runs-on: ubuntu-latest
    env:
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install PyGithub
        run: python -m pip install PyGithub==1.55

      - name: Run script
        run: python .github/scripts/set_staging_to_production_mergability_as_success.py
